metabolites_and_info = {'adp_c': {'charge': -3,
                                  'compartment': 'Cytosol',
                                  'formula': 'C10H12N5O10P2',
                                  'name': 'ADP'},
                        'aicar_c': {'charge': -2,
                                    'compartment': 'Cytosol',
                                    'formula': 'C9H13N4O8P',
                                    'name': '5-Amino-1-(5-Phospho-D-ribosyl)imidazole-4-carboxamide'},
                        'akg_c': {'charge': -2,
                                  'compartment': 'Cytosol',
                                  'formula': 'C5H4O5',
                                  'name': '2-Oxoglutarate'},
                        'amp_c': {'charge': -2,
                                  'compartment': 'Cytosol',
                                  'formula': 'C10H12N5O7P',
                                  'name': 'AMP'},
                        'atp_c': {'charge': -4,
                                  'compartment': 'Cytosol',
                                  'formula': 'C10H12N5O13P3',
                                  'name': 'ATP'},
                        'eig3p_c': {'charge': -2,
                                    'compartment': 'Cytosol',
                                    'formula': 'C6H9N2O6P',
                                    'name': 'D-erythro-1-(Imidazol-4-yl)glycerol 3-phosphate'},
                        'gln__L_c': {'charge': 0,
                                     'compartment': 'Cytosol',
                                     'formula': 'C5H10N2O3',
                                     'name': 'L-Glutamine'},
                        'glu__L_c': {'charge': -1,
                                     'compartment': 'Cytosol',
                                     'formula': 'C5H8NO4',
                                     'name': 'L-Glutamate'},
                        'h2o_c': {'charge': 0, 'compartment': 'Cytosol',
                                  'formula': 'H2O', 'name': 'H2O'},
                        'h_c': {'charge': 1, 'compartment': 'Cytosol',
                                'formula': 'H', 'name': 'H+'},
                        'his__L_c': {'charge': 0,
                                     'compartment': 'Cytosol',
                                     'formula': 'C6H9N3O2',
                                     'name': 'L-Histidine'},
                        'his__L_e': {'charge': 0,
                                     'compartment': 'e',
                                     'formula': 'C6H9N3O2',
                                     'name': 'L-Histidine'},
                        'his__L_p': {'charge': 0,
                                     'compartment': 'Periplasm',
                                     'formula': 'C6H9N3O2',
                                     'name': 'L-Histidine'},
                        'hisp_c': {'charge': -1,
                                   'compartment': 'Cytosol',
                                   'formula': 'C6H11N3O4P',
                                   'name': 'L-Histidinol phosphate'},
                        'histd_c': {'charge': 1,
                                    'compartment': 'Cytosol',
                                    'formula': 'C6H12N3O',
                                    'name': 'L-Histidinol'},
                        'imacp_c': {'charge': -2,
                                    'compartment': 'Cytosol',
                                    'formula': 'C6H7N2O5P',
                                    'name': '3-(Imidazol-4-yl)-2-oxopropyl phosphate'},
                        'nad_c': {'charge': -1,
                                  'compartment': 'Cytosol',
                                  'formula': 'C21H26N7O14P2',
                                  'name': 'Nicotinamide adenine dinucleotide'},
                        'nadh_c': {'charge': -2,
                                   'compartment': 'Cytosol',
                                   'formula': 'C21H27N7O14P2',
                                   'name': 'Nicotinamide adenine dinucleotide - reduced'},
                        'pi_c': {'charge': -2,
                                 'compartment': 'Cytosol',
                                 'formula': 'HO4P',
                                 'name': 'Phosphate'},
                        'ppi_c': {'charge': -3,
                                  'compartment': 'Cytosol',
                                  'formula': 'HO7P2',
                                  'name': 'Diphosphate'},
                        'prbamp_c': {'charge': -4,
                                     'compartment': 'Cytosol',
                                     'formula': 'C15H19N5O14P2',
                                     'name': '1-(5-Phosphoribosyl)-AMP'},
                        'prbatp_c': {'charge': -6,
                                     'compartment': 'Cytosol',
                                     'formula': 'C15H19N5O20P4',
                                     'name': '1-(5-Phosphoribosyl)-ATP'},
                        'prfp_c': {'charge': -4,
                                   'compartment': 'Cytosol',
                                   'formula': 'C15H21N5O15P2',
                                   'name': '1-(5-Phosphoribosyl)-5-[(5-phosphoribosylamino)methylideneamino]imidazole-4-carboxamide'},
                        'prlp_c': {'charge': -4,
                                   'compartment': 'Cytosol',
                                   'formula': 'C15H21N5O15P2',
                                   'name': '5-[(5-phospho-1-deoxyribulos-1-ylamino)methylideneamino]-1-(5-phosphoribosyl)imidazole-4-carboxamide'},
                        'prpp_c': {'charge': -5,
                                   'compartment': 'Cytosol',
                                   'formula': 'C5H8O14P3',
                                   'name': '5-Phospho-alpha-D-ribose 1-diphosphate'},
                        'r5p_c': {'charge': -2,
                                  'compartment': 'Cytosol',
                                  'formula': 'C5H9O8P',
                                  'name': 'alpha-D-Ribose 5-phosphate'},
                        'rib__D_c': {'charge': 0,
                                     'compartment': 'Cytosol',
                                     'formula': 'C5H10O5',
                                     'name': 'D-Ribose'},
                        'rib__D_e': {'charge': 0,
                                     'compartment': 'e',
                                     'formula': 'C5H10O5',
                                     'name': 'D-Ribose'},
                        'rib__D_p': {'charge': 0,
                                     'compartment': 'Periplasm',
                                     'formula': 'C5H10O5',
                                     'name': 'D-Ribose'}}

reactions_and_info = {
    'RIBtex': {'stoichiometry': {'rib__D_e': -1.0, 'rib__D_p': 1.0},
               'upper_bound': 1000.0, 'lower_bound': -1000.0,
               'name': 'ribose transport via diffusion (extracellular to periplasm)',
               'gene_reaction_rule': 'b0241 or b0929 or b1377 or b2215'},
    'RIBabcpp': {
        'stoichiometry': {'h2o_c': -1.0, 'atp_c': -1.0, 'rib__D_p': -1.0,
                          'pi_c': 1.0, 'h_c': 1.0, 'adp_c': 1.0,
                          'rib__D_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0,
        'name': 'D-ribose transport via ABC system (periplasm)',
        'gene_reaction_rule': '( b4231 and b4227 and b4485 and b4230 ) or ( b3749 and b3751 and b3750 and b3748 ) or ( b4087 and b4088 and b4086 )'},
    'RBK': {'stoichiometry': {'atp_c': -1.0, 'rib__D_c': -1.0, 'r5p_c': 1.0,
                              'h_c': 1.0, 'adp_c': 1.0}, 'upper_bound': 1000.0,
            'lower_bound': 0.0, 'name': 'ribokinase',
            'gene_reaction_rule': 'b3752'},
    'PRPPS': {
        'stoichiometry': {'r5p_c': -1.0, 'prpp_c': 1.0,
                          'h_c': 1.0, 'amp_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': -1000.0,
        'name': 'phosphoribosylpyrophosphate synthetase',
        'gene_reaction_rule': 'b1207'},
    'ATPPRT': {
        'stoichiometry': {'prpp_c': -1.0, 'atp_c': -1.0, 'ppi_c': 1.0,
                          'prbatp_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0, 'name': 'ATP phosphoribosyltransferase',
        'gene_reaction_rule': 'b2019'},
    'PRATPP': {
        'stoichiometry': {'h2o_c': -1.0, 'prbatp_c': -1.0, 'ppi_c': 1.0,
                          'h_c': 1.0, 'prbamp_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0, 'name': 'phosphoribosyl-ATP pyrophosphatase',
        'gene_reaction_rule': 'b2026'},
    'PRAMPC': {
        'stoichiometry': {'h2o_c': -1.0, 'prbamp_c': -1.0, 'prfp_c': 1.0},
        'upper_bound': 1000.0, 'lower_bound': 0.0,
        'name': 'phosphoribosyl-AMP cyclohydrolase',
        'gene_reaction_rule': 'b2026'},
    'PRMICI': {'stoichiometry': {'prfp_c': -1.0, 'prlp_c': 1.0},
               'upper_bound': 1000.0, 'lower_bound': -1000.0,
               'name': '1-(5-phosphoribosyl)-5-[(5-phosphoribosylamino)methylideneamino)imidazole-4-carboxamide isomerase',
               'gene_reaction_rule': 'b2024'}, 'IG3PS': {
        'stoichiometry': {'prlp_c': -1.0, 'gln__L_c': -1.0, 'glu__L_c': 1.0,
                          'h_c': 1.0, 'eig3p_c': 1.0, 'aicar_c': 1.0},
        'upper_bound': 1000.0, 'lower_bound': 0.0,
        'name': 'Imidazole-glycerol-3-phosphate synthase',
        'gene_reaction_rule': 'b2023 and b2025'},
    'IGPDH': {'stoichiometry': {'eig3p_c': -1.0, 'h2o_c': 1.0, 'imacp_c': 1.0},
              'upper_bound': 1000.0, 'lower_bound': 0.0,
              'name': 'imidazoleglycerol-phosphate dehydratase',
              'gene_reaction_rule': 'b2022'},
    'HSTPT': {
        'stoichiometry': {'glu__L_c': -1.0, 'imacp_c': -1.0, 'akg_c': 1.0,
                          'hisp_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0, 'name': 'histidinol-phosphate transaminase',
        'gene_reaction_rule': 'b2021'},
    'HISTP': {
        'stoichiometry': {'h2o_c': -1.0, 'hisp_c': -1.0, 'pi_c': 1.0,
                          'histd_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0, 'name': 'histidinol-phosphatase',
        'gene_reaction_rule': 'b2022'},
    'HISTD': {
        'stoichiometry': {'h2o_c': -1.0, 'nad_c': -2.0, 'histd_c': -1.0,
                          'his__L_c': 1.0, 'h_c': 3.0, 'nadh_c': 2.0},
        'upper_bound': 1000.0, 'lower_bound': 0.0,
        'name': 'histidinol dehydrogenase', 'gene_reaction_rule': 'b2020'},
    'HISabcpp': {
        'stoichiometry': {'h2o_c': -1.0, 'his__L_p': -1.0, 'atp_c': -1.0,
                          'pi_c': 1.0, 'his__L_c': 1.0, 'h_c': 1.0,
                          'adp_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0,
        'name': 'L-histidine transport via ABC system (periplasm)',
        'gene_reaction_rule': 'b2309 and b2307 and b2306 and b2308'},
    'HIStex': {'stoichiometry': {'his__L_e': -1.0, 'his__L_p': 1.0},
               'upper_bound': 1000.0, 'lower_bound': -1000.0,
               'name': 'L-histidine transport via diffusion (extracellular to periplasm)',
               'gene_reaction_rule': 'b0241 or b0929 or b1377 or b2215'}}
