carbon_sources = \
    ['EX_12ppd__S_e', 'EX_14glucan_e', 'EX_3hcinnm_e', 'EX_3hpppn_e', 'EX_5dglcn_e',
     'LalaDgluMdap_e', 'EX_acac_e', 'EX_acgal_e', 'EX_acgal1p_e', 'EX_akg_e',
     'all__D_e', 'EX_alltn_e', 'EX_arab__L_e', 'EX_ascb__L_e', 'EX_but_e', 'EX_butso3_e',
     'chol_e', 'EX_csn_e', 'EX_cys__D_e', 'EX_etha_e', 'EX_fald_e', 'EX_fe3dcit_e',
     'frulys_e', 'EX_fruur_e', 'EX_fuc__L_e', 'EX_g1p_e', 'EX_gal_e', 'EX_gal_bD_e',
     'gal1p_e', 'EX_galct__D_e', 'EX_galctn__D_e', 'EX_galctn__L_e', 'EX_galt_e',
     'galur_e', 'EX_glcur_e', 'EX_glcur1p_e', 'EX_glyclt_e', 'EX_idon__L_e',
     'lyx__L_e', 'EX_malt_e', 'EX_malthx_e', 'EX_maltpt_e', 'EX_malttr_e',
     'maltttr_e', 'EX_manglyc_e', 'EX_melib_e', 'EX_orot_e', 'EX_pacald_e', 'EX_peamn_e',
     'ppa_e', 'EX_ppal_e', 'EX_pppn_e', 'EX_psclys_e', 'EX_r5p_e', 'EX_rib__D_e',
     'rmn_e', 'EX_sbt__D_e', 'EX_sucr_e', 'EX_tartr__D_e', 'EX_trp__L_e', 'EX_uacgam_e',
     'udpacgal_e', 'EX_udpg_e', 'EX_udpgal_e', 'EX_udpglcur_e', 'EX_ura_e', 'EX_xan_e',
     'xyl__D_e', 'EX_xylu__L_e', 'EX_4hphac_e', 'EX_4hthr_e', 'EX_oaa_e', 'EX_drib_e',
     '2pg_e', 'EX_3pg_e', 'EX_3hoxpac_e', 'EX_galam_e', 'EX_raffin_e', 'EX_arab__D_e']

phosphorus_sources = \
    ['EX_pi_e', 'EX_fmn_e', 'EX_amp_e', 'EX_g6p_e', 'EX_cbl1_e', 'EX_nmn_e',
     'EX_f6p_e', 'EX_glyc3p_e', 'EX_gam6p_e', 'EX_minohp_e', 'EX_ppt_e',
     'EX_gdp_e', 'EX_gtp_e', 'EX_fad_e', 'EX_adocbl_e', 'EX_23camp_e',
     'EX_23cgmp_e', 'EX_23cump_e', 'EX_3amp_e', 'EX_3gmp_e', 'EX_3ump_e',
     'EX_eca4colipa_e', 'EX_imp_e', 'EX_gmp_e', 'EX_ump_e', 'EX_enlipa_e',
     'EX_hacolipa_e', 'EX_r5p_e', 'EX_glyc2p_e', 'EX_halipa_e', 'EX_cmp_e',
     'EX_acgam1p_e', 'EX_glcur1p_e', 'EX_thrp_e', 'EX_dump_e', 'EX_gal1p_e',
     'EX_dcmp_e', 'EX_23ccmp_e', 'EX_3cmp_e', 'EX_g3pe_e', 'EX_acgal1p_e',
     'EX_tyrp_e', 'EX_uacgam_e', 'EX_udpacgal_e', 'EX_udpg_e', 'EX_udpgal_e',
     'EX_udpglcur_e', 'EX_pser__L_e', 'EX_g3pc_e', 'EX_g3pg_e', 'EX_g3pi_e',
     'EX_g3ps_e', 'EX_xmp_e', 'EX_damp_e', 'EX_dimp_e', 'EX_dgmp_e',
     'EX_man6p_e', 'EX_g1p_e', 'EX_dtmp_e', 'EX_mepn_e']


strain_classification = {'iLF82_1304': 'InPec',
                         'iNRG857_1313': 'InPec',
                         'iUMN146_1321': 'InPec',
                         'iAPECO1_1312': 'ExPec',
                         'iEcolC_1368': 'Commensal',
                         'iECB_1328': 'Commensal',
                         'iECBD_1354': 'Commensal',
                         'iB21_1397': 'Commensal',
                         'iECD_1391': 'Commensal',
                         'iBWG_1329': 'Commensal',
                         'iEcDH1_1363': 'Commensal',
                         'iECDH1ME8569_1439': 'Commensal',
                         'iECED1_1282': 'Commensal',
                         'iEcHS_1320': 'Commensal',
                         'iECIAI1_1343': 'Commensal',
                         'iEKO11_1354': 'Commensal',
                         'iECSE_1348': 'Commensal',
                         'iECSF_1327': 'Commensal',
                         'iECDH10B_1368': 'Commensal',
                         'iJO1366': 'Commensal',
                         'iY75_1357': 'Commensal',
                         'iECW_1372': 'Commensal',
                         'iWFL_1372': 'Commensal',
                         'iEC042_1314': 'InPec',
                         'iEC55989_1330': 'InPec',
                         'iECO103_1326': 'InPec',
                         'iECO111_1330': 'InPec',
                         'iECH74115_1262': 'InPec',
                         'iZ_1308': 'InPec',
                         'iECs_1301': 'InPec',
                         'iECSP_1301': 'InPec',
                         'iECO26_1355': 'InPec',
                         'iG2583_1286': 'InPec',
                         'iEcSMS35_1347': 'ExPec',
                         'iE2348C_1286': 'InPec',
                         'iEcE24377_1341': 'InPec',
                         'iETEC_1333': 'InPec',
                         'iUMNK88_1353': 'InPec',
                         'iECOK1_1307': 'ExPec',
                         'iECS88_1305': 'ExPec',
                         'iECP_1309': 'ExPec',
                         'iECABU_c1320': 'ExPec',
                         'ic_1306': 'ExPec',
                         'iECIAI39_1322': 'ExPec',
                         'iECNA114_1301': 'ExPec',
                         'iECUMN_1333': 'ExPec',
                         'iUTI89_1310': 'ExPec'}