carbon_sources = \
    ['12ppd__S_e', '14glucan_e', '3hcinnm_e', '3hpppn_e', '5dglcn_e',
     'LalaDgluMdap_e', 'acac_e', 'acgal_e', 'acgal1p_e', 'akg_e',
     'all__D_e', 'alltn_e', 'arab__L_e', 'ascb__L_e', 'but_e', 'butso3_e',
     'chol_e', 'csn_e', 'cys__D_e', 'etha_e', 'fald_e', 'fe3dcit_e',
     'frulys_e', 'fruur_e', 'fuc__L_e', 'g1p_e', 'gal_e', 'gal_bD_e',
     'gal1p_e', 'galct__D_e', 'galctn__D_e', 'galctn__L_e', 'galt_e',
     'galur_e', 'glcur_e', 'glcur1p_e', 'glyclt_e', 'idon__L_e',
     'lyx__L_e', 'malt_e', 'malthx_e', 'maltpt_e', 'malttr_e',
     'maltttr_e', 'manglyc_e', 'melib_e', 'orot_e', 'pacald_e', 'peamn_e',
     'ppa_e', 'ppal_e', 'pppn_e', 'psclys_e', 'r5p_e', 'rib__D_e',
     'rmn_e', 'sbt__D_e', 'sucr_e', 'tartr__D_e', 'trp__L_e', 'uacgam_e',
     'udpacgal_e', 'udpg_e', 'udpgal_e', 'udpglcur_e', 'ura_e', 'xan_e',
     'xyl__D_e', 'xylu__L_e', '4hphac_e', '4hthr_e', 'oaa_e', 'drib_e',
     '2pg_e', '3pg_e', '3hoxpac_e', 'galam_e', 'raffin_e', 'arab__D_e']

strain_classification = {'iLF82_1304': 'InPec',
                         'iNRG857_1313': 'InPec',
                         'iUMN146_1321': 'InPec',
                         'iAPECO1_1312': 'ExPec',
                         'iEcolC_1368': 'Commensal',
                         'iECB_1328': 'Commensal',
                         'iECBD_1354': 'Commensal',
                         'iB21_1397': 'Commensal',
                         'iECD_1391': 'Commensal',
                         'iBWG_1329': 'Commensal',
                         'iEcDH1_1363': 'Commensal',
                         'iECDH1ME8569_1439': 'Commensal',
                         'iECED1_1282': 'Commensal',
                         'iEcHS_1320': 'Commensal',
                         'iECIAI1_1343': 'Commensal',
                         'iEKO11_1354': 'Commensal',
                         'iECSE_1348': 'Commensal',
                         'iECSF_1327': 'Commensal',
                         'iECDH10B_1368': 'Commensal',
                         'iJO1366': 'Commensal',
                         'iY75_1357': 'Commensal',
                         'iECW_1372': 'Commensal',
                         'iWFL_1372': 'Commensal',
                         'iEC042_1314': 'InPec',
                         'iEC55989_1330': 'InPec',
                         'iECO103_1326': 'InPec',
                         'iECO111_1330': 'InPec',
                         'iECH74115_1262': 'InPec',
                         'iZ_1308': 'InPec',
                         'iECs_1301': 'InPec',
                         'iECSP_1301': 'InPec',
                         'iECO26_1355': 'InPec',
                         'iG2583_1286': 'InPec',
                         'iEcSMS35_1347': 'ExPec',
                         'iE2348C_1286': 'InPec',
                         'iEcE24377_1341': 'InPec',
                         'iETEC_1333': 'InPec',
                         'iUMNK88_1353': 'InPec',
                         'iECOK1_1307': 'ExPec',
                         'iECS88_1305': 'ExPec',
                         'iECP_1309': 'ExPec',
                         'iECABU_c1320': 'ExPec',
                         'ic_1306': 'ExPec',
                         'iECIAI39_1322': 'ExPec',
                         'iECNA114_1301': 'ExPec',
                         'iECUMN_1333': 'ExPec',
                         'iUTI89_1310': 'ExPec'}